/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry_payment;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Form_laundry extends javax.swing.JFrame {

    /**
     * Creates new form Form_laundry
     */
    public Form_laundry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CbJenis = new javax.swing.JComboBox<>();
        TxtHarga = new javax.swing.JTextField();
        TxtBerat = new javax.swing.JTextField();
        TxtTotal = new javax.swing.JTextField();
        TxtBayar = new javax.swing.JTextField();
        BtTransaksi = new javax.swing.JButton();
        BtBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Laundry Payment");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Total Harga");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Berat");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Jenis Cuci");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Bayar");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Harga Per kilo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        CbJenis.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "CUCI KERING", "CUCI BASAH", "CUCI SETRIKA" }));
        CbJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbJenisActionPerformed(evt);
            }
        });
        jPanel1.add(CbJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 170, 30));

        TxtHarga.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TxtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtHargaActionPerformed(evt);
            }
        });
        jPanel1.add(TxtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 170, 30));

        TxtBerat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TxtBerat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtBeratKeyReleased(evt);
            }
        });
        jPanel1.add(TxtBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 170, 30));

        TxtTotal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(TxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 170, 30));

        TxtBayar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TxtBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBayarActionPerformed(evt);
            }
        });
        jPanel1.add(TxtBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 170, 30));

        BtTransaksi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BtTransaksi.setText("TRANSAKSI");
        BtTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtTransaksiActionPerformed(evt);
            }
        });
        jPanel1.add(BtTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, -1, -1));

        BtBatal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BtBatal.setText("BATAL");
        BtBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBatalActionPerformed(evt);
            }
        });
        jPanel1.add(BtBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 130, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 690);

        setSize(new java.awt.Dimension(639, 744));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtHargaActionPerformed

    private void TxtBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBayarActionPerformed

    private void CbJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbJenisActionPerformed
        // TODO add your handling code here:
        if(CbJenis.getSelectedItem().toString().equalsIgnoreCase("CUCI KERING")) {
            TxtHarga.setText("4000");
        } else if(CbJenis.getSelectedItem().toString().equalsIgnoreCase("CUCI BASAH")) {
            TxtHarga.setText("3000");
        } else if(CbJenis.getSelectedItem().toString().equalsIgnoreCase("CUCI SETRIKA")) {
            TxtHarga.setText("5000");
        }
    }//GEN-LAST:event_CbJenisActionPerformed

    private void BtTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtTransaksiActionPerformed
        // TODO add your handling code here:
        int bayar = Integer.parseInt(TxtBayar.getText());
        int total_harga = Integer.parseInt(TxtTotal.getText());
        double kembalian = bayar - total_harga;
        String kembali = Integer.toString((int) kembalian);
        JOptionPane.showMessageDialog(null, "Kembalian Anda : \n"+kembalian);
        
        CbJenis.setSelectedItem("PILIH");
        TxtHarga.setText("");
        TxtBerat.setText("");
        TxtTotal.setText("");
        TxtBayar.setText("");
    }//GEN-LAST:event_BtTransaksiActionPerformed

    private void TxtBeratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBeratKeyReleased
        // TODO add your handling code here:
        int harga = Integer.parseInt(TxtHarga.getText());
        int berat = Integer.parseInt(TxtBerat.getText());
        double totalbyr = harga*berat;
        String total = Integer.toString((int) totalbyr);
        TxtTotal.setText(total);
    }//GEN-LAST:event_TxtBeratKeyReleased

    private void BtBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBatalActionPerformed
        // TODO add your handling code here:
        CbJenis.setSelectedItem("PILIH");
        TxtHarga.setText("");
        TxtBerat.setText("");
        TxtTotal.setText("");
        TxtBayar.setText("");
    }//GEN-LAST:event_BtBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_laundry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBatal;
    private javax.swing.JButton BtTransaksi;
    private javax.swing.JComboBox<String> CbJenis;
    private javax.swing.JTextField TxtBayar;
    private javax.swing.JTextField TxtBerat;
    private javax.swing.JTextField TxtHarga;
    private javax.swing.JTextField TxtTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
